### ISSUE TITLE
Birthdate Issue

### ISSUE THREAD

**Issue by hitenzaptech** [Sila-Money/sila-sdk-php#1]
Hello Sila Team,
I am getting the following error while passing the birthdate as shown in the example in sdk. can you please look into this.

Uncaught TypeError: Argument 13 passed to Silamoney\Client\Domain\User::__construct() must be an instance of Silamoney\Client\Domain\Date, instance of DateTime given, called in /var/www/html/sila-api/index.php on line 38 and defined in /var/www/html/sila-api/vendor/silamoney/php-sdk/lib/Domain/User.php:104

**Comment by ncavet** [comment]
Make sure your passing date in the format: “YYYY-MM-DD" and the date is in the past.

**Comment by brukeg** [comment]
@hitenzaptech If this doesn't work for you please let us know.

**Comment by hitenzaptech** [comment]
Still not working ..

**Comment by isaacavery** [comment]
Apologies, this was closed by mistake. We have identified the issues and our team is performing the necessary updates. We will release the update as soon as that is complete.

**Comment by hitenzaptech** [comment]
okay thanks for the response. The syntax is wrong for passing the birthdate. so pls look into it.

Also i found one more issue:

Please do following :
1)go to this link :https://guide.silamoney.com/api/accounts/create-account
2) click on the Customer Dashboard link in menu
3) it redirects me to the some youtube video and one guy is dancing...

**Comment by isaacavery** [comment]
Fixed in `0.2.3-alpha`

**Comment by brukeg** [comment]
@hitenzaptech this one should be resolved now too. Give us a shout if you continue to experience any issues.
