### ISSUE TITLE
Blockchain address issue

### ISSUE THREAD

**Issue by arshadanjum167** [Sila-Money/sila-sdk-php#13]
Hello Sila Team,
I am using php sdk for creating new user but i am getting the following error :

I am getting "Please choose a different blockchain address to register" while using register endpoint.

Response:
+"message": "Please choose a different blockchain address to register."
    +"reference": "c9977150-cfdc-4a74-9d33-c40b8dabf107"
    +"status": "FAILURE"

**Comment by brukeg** [comment]
Greetings! This error means the Ethereum address has already been successfully registered. You'll need to try again with a different address.

**Comment by arshadanjum167** [comment]
Can you please give how to make blockchain adress?

**Comment by isaacavery** [comment]
You can use the Generate Wallet functionality: https://github.com/Sila-Money/sila-sdk-php#generate-wallet

**Comment by arshadanjum167** [comment]
When i used generate wallet it give ERROR: Failed to generate private key. -> error:02001003:system library:fopen:No such process
$wallet = $client->generateWallet();
$gaddress= $wallet->getAddress();        // e.g. 0x9ae1e2a685c5f23981757ea0cb6f5b413aa5f29f
$gprivatekey =$wallet->getPrivateKey();

**Comment by arshadanjum167** [comment]
Anyone has idea...what is the wrong i am doing?

**Comment by brukeg** [comment]
@arshadanjum167 what happens when you do the below, and what version of the SDK are you using? It should be 2.9-rc

```.php
$wallet = $client->generateWallet();
$print $wallet->getAddress(); // e.g. 0x9ae1e2a685c5f23981757ea0cb6f5b413aa5f29f
$print $wallet->getPrivateKey();
```

The second option is if you already have an ethereum address and private key. You can try that method with https://vanity-eth.tk/ or you can use a browser extension called Metamask, but these are not likely going to help you do anything other than some testing.
