### ISSUE TITLE
Intialization Issue

### ISSUE THREAD

**Issue by hitenzaptech** [Sila-Money/sila-sdk-php#2]
Hello Sila Team,
Please check the bold line, from where i can get the **$apphandler** variable as i am not seeing it assigned anywhere.
require_once 'vendor/autoload.php';

use Silamoney\Client\Api\SilaApi;
use Silamoney\Client\Domain\{BalanceEnvironments,Environments};

// Load your credentials
$appHandle = 'your app handle';
$privateKey = 'your private key';

// Create your client
$client = new SilaApi('your sila endpoint url', 'your sila balance endpoint url', $appHandle, $privateKey); // From custom URL
**$client = SilaApi::fromEnvironment(Environments::SANDBOX, BalanceEnvironments::SANDBOX, $appHandler, $privateKey); // From predefined environments**
$client = SilaApi::fromDefault($appHandle, $privateKey); // From default sandbox environments

**Comment by ncavet** [comment]
@hitenzaptech - $AppHandler should be $appHandle - this is the app name created in console.silamoney.com

![image](https://user-images.githubusercontent.com/3806002/73912373-30759680-4869-11ea-9371-79aa2edd4aca.png)

**Comment by brukeg** [comment]
@hitenzaptech I'm looking into this now. I think it was a typo that we'll need to fix. Let us know if you still can't authenticate.

**Comment by isaacavery** [comment]
Fixed in `0.2.3-alpha`

**Comment by brukeg** [comment]
@hitenzaptech this should be resolved now. Let us know if you continue to experience any issues.
