### ISSUE TITLE
SSN Number validation issue

### ISSUE THREAD

**Issue by hitenzaptech** [Sila-Money/sila-sdk-php#3]
Hello Sila Team, 
I am using php sdk for creating new user but i am getting the following error :

**Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://sandbox.silamoney.com/0.2/register` resulted in a `400 Bad Request` response: {"validation_details":{"identity":"Input did not match SSN regex pattern (^(?!123([ -]?)45([ -]?)6789)(?!\\b(\\d)\\3+\\b (truncated...)**

I have tried with/out hyphens but still getting the SSN number validation issue. so please look into it.

**Comment by ncavet** [comment]
Can you confirm you are using the value I. The specs doc. 

123452222

**Comment by isaacavery** [comment]
This is resolved as of 0.2.4-beta.

**Comment by mcalm1511** [comment]
Hello Sila Team,
I am using php sdk for creating new user but i am getting the following error :
-data: {#458 ▼
    +"validation_details": {#417 ▼
      +"identity": "Input did not match SSN regex pattern."
      +"crypto_entry": {#307 ▼
        +"crypto_address": "This value does not match the required address pattern: ^0x[a-fA-F0-9]{40}$"
      }
    }
    +"message": "Bad request."
    +"status": "FAILURE"
  }
I enter in ssn number is : 541-98-5030

**Comment by ncavet** [comment]
Hi its failing because you should pass the SSN with no hyphens. See this
help article:
http://help.silamoney.com/en/articles/4260516-what-field-validations-are-used-in-the-sila-api
