### ISSUE TITLE
Get transaction API not working

### ISSUE THREAD

**Issue by mayuriOAB** [Sila-Money/sila-sdk-php#4]
Hello team, 
when I was tried to get response from getTransactions() API. It was throwing error like:
response error: Client error: POST https: //sandbox.silamoney.com/0.2/redeem_sila resulted in a 400 Bad Request response: { "validation_details": { "message": "'get_transactions_msg' is not a valid choice. Must be one of: ['redeem_msg']"

So I checked API file (SilaApi.php > getTransactions() ) of SDK and changed methods line
$path = '/redeem_sila'; 
to 
$path = '/get_transactions';
And then its working as expected.
Please do update this as soon as possible, so no new comer will face same problem again.

Thanks.
![Screenshot (5)](https://user-images.githubusercontent.com/13747426/74723384-7dda0680-5260-11ea-8d94-8659481bee14.png)

**Comment by brukeg** [comment]
Thank you @mayuriOAB, we're deploying a fix for this very soon.

**Comment by isaacavery** [comment]
This is resolved as of 0.2.4-beta.

**Comment by mayuriOAB** [comment]
Okay Thanks for quick fix.
