### ISSUE TITLE
do you support achNow product endpoint .. if not do update so

### ISSUE THREAD

**Issue by RakeshShresthaNP** [Sila-Money/sila-sdk-php#56]

**Comment by RakeshShresthaNP** [comment]
New product: ACHNow

Sila introduces our newest product, ACHNow, to turn regular ACH transactions into instant ones! For more, please see our documentation [here](https://docs.silamoney.com/docs/achnow).

**Comment by estara** [comment]
No, the SDKs do not support the /transact endpoint. At this point in time we will not be adding any new endpoints to the SDKs, they will only receive bugfixes and security patches. We strongly recommend customers currently using the SDKs begin to work on transitioning to using JWT authentication as we will be sunsetting the SDKs.
